@host= http://localhost:5259
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOTAyYzkzZC05MzM5LTQ0YjItYmEyNy02Y2Y0MmU0MGZhYTciLCJnaXZlbl9uYW1lIjoiQWxleGFuZHJlIiwiZmFtaWx5X25hbWUiOiJDb3RpZXIiLCJqdGkiOiIzMTRiMGI3Yi0zNzhhLTQzYmItODU3ZS1hNzYyMTE4YjFhNTEiLCJleHAiOjE3MTQyOTQwOTAsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.X_k6BqUL4grPMDQhvvCY7CVSMSewOYIkImaRtsPTxrA
POST {{host}}/rooms
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Chambre 21",
    "description" : "Chambre simple pour une personne tristement célibataire",
    "price" : 100,
    "capacity" : 1,
    "bedroomType" : "Simple"
}